language: node_js
node_js:
  - 12
os:
  - windows
  - osx
  - linux
osx_image: xcode10.2
git:
  depth: false
script:
  - "bash ./build.sh"
before_deploy:	
- git config --local user.name "RobinSchapendonkGames"	
- git config --local user.email "ytrobinsch2@gmail.com"	
- export TRAVIS_TAG=v0.0.1	
- git tag $TRAVIS_TAG
deploy:	
  provider: releases	
  api_key: $GITHUB_TOKEN	
  skip_cleanup: true	
  draft: true 